#%RAML 1.0
title: "Example of type bindings"
mediaType: application/json
uses:
  types: ./typeExtras.raml
  crud: ./crud.raml
types:
  Person:
    properties:
      id?:
        type: integer
        (types.Id):
        (types.RequiredIn): [ listView, detailsView]
        (types.DisallowedIn): [ create]
      name:
        type: string
      lastName:
        type: string
      friends?:
        (types.VisibleIn): detailsView
        type: Person[]

/persons:
  type:  { crud.collection: {MemberType : Person} }
  /{id}:
    type:  { crud.item: {Type : Person} }
