#%RAML 1.0 Library
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
(commons.Id):  org.aml.ramltypes
(commons.Title): RAML Types
usage: This library describes set of raml types
annotationTypes:
  Library: RamlTypeLibrary
types:
  RamlTypeLibrary:
      type: object
      description: Library containing types and annotation types
      properties:
        uses:
          description: Libraries used by this library
          properties:
            //:
              description: Libraries used by this library
              type: LibraryReference
        types:
          description: Data types declared by this library
          properties:
            //:
              displayName: Types
              description: Types declared by this library
              type: RamlDataType
        annotationTypes:
          description: Annotation types declared by this library
          properties:
            //: 
              type: RamlDataType
              description: Annotation Types declared by this library
  RamlDataType:
    type: object
    displayName: Type
    properties:
      facets?:
        type: object
        description: Facets of this type
        properties:
          //: RamlProperty
      type: TypeExpression[] | TypeExpression
      description:
        type: commons.GitHubFlavoredMarkdown
        description: Human readable description
      displayName: string
  RamlProperty:
    type: RamlDataType
    properties:
      required?:
         type: boolean
         default: false
         required: true
  RamlObjectType:
    type: RamlDataType
    properties:
      discriminator?: string
      properties?:
        type: object
        properties:
          //: RamlProperty
      minProperties?: integer
      maxProperties?: integer
  RamlArrayType:
    type: RamlDataType
    properties:
      items: RamlDataTypeRef
      minItems?:
        required: true
      maxItems?: integer
      uniqueItems?: boolean
  RamlBooleanType:
    type: RamlDataType
  RamlStringType:
    type: RamlDataType
    properties:
      pattern?: integer
      minLength?: integer
      maxLength?: integer
      enum?: string[]
  RamlNumberType:
    type: RamlDataType
    properties:
      minumum?: integer
      maximum?: integer
      multipleOf?: number
      enum?: string[]
  LibraryReference: string
  TypeExpression: string
  RamlDataTypeRef: TypeExpression | RamlDataType
